//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.serviceSoap")]
    public interface serviceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  P_DATE_from 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllVendors", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.GetAllVendorsResponse GetAllVendors(ConsoleApp1.ServiceReference1.GetAllVendorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllVendors", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllVendorsResponse> GetAllVendorsAsync(ConsoleApp1.ServiceReference1.GetAllVendorsRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetAllWarehousesResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWarehouses", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.GetAllWarehousesResponse GetAllWarehouses(ConsoleApp1.ServiceReference1.GetAllWarehousesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWarehouses", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllWarehousesResponse> GetAllWarehousesAsync(ConsoleApp1.ServiceReference1.GetAllWarehousesRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  P_DATE_from 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.GetAllProductsResponse GetAllProducts(ConsoleApp1.ServiceReference1.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllProductsResponse> GetAllProductsAsync(ConsoleApp1.ServiceReference1.GetAllProductsRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  ProductsList 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProductsByID", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.GetAllProductsByIDResponse GetAllProductsByID(ConsoleApp1.ServiceReference1.GetAllProductsByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProductsByID", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllProductsByIDResponse> GetAllProductsByIDAsync(ConsoleApp1.ServiceReference1.GetAllProductsByIDRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  P_DATE 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStock", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.GetAllStockResponse GetAllStock(ConsoleApp1.ServiceReference1.GetAllStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStock", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllStockResponse> GetAllStockAsync(ConsoleApp1.ServiceReference1.GetAllStockRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  P_DATE 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPrice", ReplyAction="*")]
        ConsoleApp1.ServiceReference1.GetAllPriceResponse GetAllPrice(ConsoleApp1.ServiceReference1.GetAllPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllPriceResponse> GetAllPriceAsync(ConsoleApp1.ServiceReference1.GetAllPriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllVendorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllVendors", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllVendorsRequestBody Body;
        
        public GetAllVendorsRequest() {
        }
        
        public GetAllVendorsRequest(ConsoleApp1.ServiceReference1.GetAllVendorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllVendorsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_DATE_from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_DATE_TO;
        
        public GetAllVendorsRequestBody() {
        }
        
        public GetAllVendorsRequestBody(string P_DATE_from, string P_DATE_TO) {
            this.P_DATE_from = P_DATE_from;
            this.P_DATE_TO = P_DATE_TO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllVendorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllVendorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllVendorsResponseBody Body;
        
        public GetAllVendorsResponse() {
        }
        
        public GetAllVendorsResponse(ConsoleApp1.ServiceReference1.GetAllVendorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllVendorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllVendorsResult;
        
        public GetAllVendorsResponseBody() {
        }
        
        public GetAllVendorsResponseBody(string GetAllVendorsResult) {
            this.GetAllVendorsResult = GetAllVendorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWarehousesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWarehouses", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllWarehousesRequestBody Body;
        
        public GetAllWarehousesRequest() {
        }
        
        public GetAllWarehousesRequest(ConsoleApp1.ServiceReference1.GetAllWarehousesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllWarehousesRequestBody {
        
        public GetAllWarehousesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWarehousesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWarehousesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllWarehousesResponseBody Body;
        
        public GetAllWarehousesResponse() {
        }
        
        public GetAllWarehousesResponse(ConsoleApp1.ServiceReference1.GetAllWarehousesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWarehousesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllWarehousesResult;
        
        public GetAllWarehousesResponseBody() {
        }
        
        public GetAllWarehousesResponseBody(string GetAllWarehousesResult) {
            this.GetAllWarehousesResult = GetAllWarehousesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllProductsRequestBody Body;
        
        public GetAllProductsRequest() {
        }
        
        public GetAllProductsRequest(ConsoleApp1.ServiceReference1.GetAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_DATE_from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_DATE_TO;
        
        public GetAllProductsRequestBody() {
        }
        
        public GetAllProductsRequestBody(string P_DATE_from, string P_DATE_TO) {
            this.P_DATE_from = P_DATE_from;
            this.P_DATE_TO = P_DATE_TO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllProductsResponseBody Body;
        
        public GetAllProductsResponse() {
        }
        
        public GetAllProductsResponse(ConsoleApp1.ServiceReference1.GetAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllProductsResult;
        
        public GetAllProductsResponseBody() {
        }
        
        public GetAllProductsResponseBody(string GetAllProductsResult) {
            this.GetAllProductsResult = GetAllProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsByID", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllProductsByIDRequestBody Body;
        
        public GetAllProductsByIDRequest() {
        }
        
        public GetAllProductsByIDRequest(ConsoleApp1.ServiceReference1.GetAllProductsByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProductsList;
        
        public GetAllProductsByIDRequestBody() {
        }
        
        public GetAllProductsByIDRequestBody(string ProductsList) {
            this.ProductsList = ProductsList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllProductsByIDResponseBody Body;
        
        public GetAllProductsByIDResponse() {
        }
        
        public GetAllProductsByIDResponse(ConsoleApp1.ServiceReference1.GetAllProductsByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllProductsByIDResult;
        
        public GetAllProductsByIDResponseBody() {
        }
        
        public GetAllProductsByIDResponseBody(string GetAllProductsByIDResult) {
            this.GetAllProductsByIDResult = GetAllProductsByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStock", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllStockRequestBody Body;
        
        public GetAllStockRequest() {
        }
        
        public GetAllStockRequest(ConsoleApp1.ServiceReference1.GetAllStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_DATE;
        
        public GetAllStockRequestBody() {
        }
        
        public GetAllStockRequestBody(string P_DATE) {
            this.P_DATE = P_DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllStockResponseBody Body;
        
        public GetAllStockResponse() {
        }
        
        public GetAllStockResponse(ConsoleApp1.ServiceReference1.GetAllStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllStockResult;
        
        public GetAllStockResponseBody() {
        }
        
        public GetAllStockResponseBody(string GetAllStockResult) {
            this.GetAllStockResult = GetAllStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPrice", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllPriceRequestBody Body;
        
        public GetAllPriceRequest() {
        }
        
        public GetAllPriceRequest(ConsoleApp1.ServiceReference1.GetAllPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_DATE;
        
        public GetAllPriceRequestBody() {
        }
        
        public GetAllPriceRequestBody(string P_DATE) {
            this.P_DATE = P_DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReference1.GetAllPriceResponseBody Body;
        
        public GetAllPriceResponse() {
        }
        
        public GetAllPriceResponse(ConsoleApp1.ServiceReference1.GetAllPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllPriceResult;
        
        public GetAllPriceResponseBody() {
        }
        
        public GetAllPriceResponseBody(string GetAllPriceResult) {
            this.GetAllPriceResult = GetAllPriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviceSoapChannel : ConsoleApp1.ServiceReference1.serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviceSoapClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.serviceSoap>, ConsoleApp1.ServiceReference1.serviceSoap {
        
        public serviceSoapClient() {
        }
        
        public serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.GetAllVendorsResponse ConsoleApp1.ServiceReference1.serviceSoap.GetAllVendors(ConsoleApp1.ServiceReference1.GetAllVendorsRequest request) {
            return base.Channel.GetAllVendors(request);
        }
        
        public string GetAllVendors(string P_DATE_from, string P_DATE_TO) {
            ConsoleApp1.ServiceReference1.GetAllVendorsRequest inValue = new ConsoleApp1.ServiceReference1.GetAllVendorsRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllVendorsRequestBody();
            inValue.Body.P_DATE_from = P_DATE_from;
            inValue.Body.P_DATE_TO = P_DATE_TO;
            ConsoleApp1.ServiceReference1.GetAllVendorsResponse retVal = ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllVendors(inValue);
            return retVal.Body.GetAllVendorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllVendorsResponse> ConsoleApp1.ServiceReference1.serviceSoap.GetAllVendorsAsync(ConsoleApp1.ServiceReference1.GetAllVendorsRequest request) {
            return base.Channel.GetAllVendorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllVendorsResponse> GetAllVendorsAsync(string P_DATE_from, string P_DATE_TO) {
            ConsoleApp1.ServiceReference1.GetAllVendorsRequest inValue = new ConsoleApp1.ServiceReference1.GetAllVendorsRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllVendorsRequestBody();
            inValue.Body.P_DATE_from = P_DATE_from;
            inValue.Body.P_DATE_TO = P_DATE_TO;
            return ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllVendorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.GetAllWarehousesResponse ConsoleApp1.ServiceReference1.serviceSoap.GetAllWarehouses(ConsoleApp1.ServiceReference1.GetAllWarehousesRequest request) {
            return base.Channel.GetAllWarehouses(request);
        }
        
        public string GetAllWarehouses() {
            ConsoleApp1.ServiceReference1.GetAllWarehousesRequest inValue = new ConsoleApp1.ServiceReference1.GetAllWarehousesRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllWarehousesRequestBody();
            ConsoleApp1.ServiceReference1.GetAllWarehousesResponse retVal = ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllWarehouses(inValue);
            return retVal.Body.GetAllWarehousesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllWarehousesResponse> ConsoleApp1.ServiceReference1.serviceSoap.GetAllWarehousesAsync(ConsoleApp1.ServiceReference1.GetAllWarehousesRequest request) {
            return base.Channel.GetAllWarehousesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllWarehousesResponse> GetAllWarehousesAsync() {
            ConsoleApp1.ServiceReference1.GetAllWarehousesRequest inValue = new ConsoleApp1.ServiceReference1.GetAllWarehousesRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllWarehousesRequestBody();
            return ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllWarehousesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.GetAllProductsResponse ConsoleApp1.ServiceReference1.serviceSoap.GetAllProducts(ConsoleApp1.ServiceReference1.GetAllProductsRequest request) {
            return base.Channel.GetAllProducts(request);
        }
        
        public string GetAllProducts(string P_DATE_from, string P_DATE_TO) {
            ConsoleApp1.ServiceReference1.GetAllProductsRequest inValue = new ConsoleApp1.ServiceReference1.GetAllProductsRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllProductsRequestBody();
            inValue.Body.P_DATE_from = P_DATE_from;
            inValue.Body.P_DATE_TO = P_DATE_TO;
            ConsoleApp1.ServiceReference1.GetAllProductsResponse retVal = ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllProducts(inValue);
            return retVal.Body.GetAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllProductsResponse> ConsoleApp1.ServiceReference1.serviceSoap.GetAllProductsAsync(ConsoleApp1.ServiceReference1.GetAllProductsRequest request) {
            return base.Channel.GetAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllProductsResponse> GetAllProductsAsync(string P_DATE_from, string P_DATE_TO) {
            ConsoleApp1.ServiceReference1.GetAllProductsRequest inValue = new ConsoleApp1.ServiceReference1.GetAllProductsRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllProductsRequestBody();
            inValue.Body.P_DATE_from = P_DATE_from;
            inValue.Body.P_DATE_TO = P_DATE_TO;
            return ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.GetAllProductsByIDResponse ConsoleApp1.ServiceReference1.serviceSoap.GetAllProductsByID(ConsoleApp1.ServiceReference1.GetAllProductsByIDRequest request) {
            return base.Channel.GetAllProductsByID(request);
        }
        
        public string GetAllProductsByID(string ProductsList) {
            ConsoleApp1.ServiceReference1.GetAllProductsByIDRequest inValue = new ConsoleApp1.ServiceReference1.GetAllProductsByIDRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllProductsByIDRequestBody();
            inValue.Body.ProductsList = ProductsList;
            ConsoleApp1.ServiceReference1.GetAllProductsByIDResponse retVal = ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllProductsByID(inValue);
            return retVal.Body.GetAllProductsByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllProductsByIDResponse> ConsoleApp1.ServiceReference1.serviceSoap.GetAllProductsByIDAsync(ConsoleApp1.ServiceReference1.GetAllProductsByIDRequest request) {
            return base.Channel.GetAllProductsByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllProductsByIDResponse> GetAllProductsByIDAsync(string ProductsList) {
            ConsoleApp1.ServiceReference1.GetAllProductsByIDRequest inValue = new ConsoleApp1.ServiceReference1.GetAllProductsByIDRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllProductsByIDRequestBody();
            inValue.Body.ProductsList = ProductsList;
            return ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllProductsByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.GetAllStockResponse ConsoleApp1.ServiceReference1.serviceSoap.GetAllStock(ConsoleApp1.ServiceReference1.GetAllStockRequest request) {
            return base.Channel.GetAllStock(request);
        }
        
        public string GetAllStock(string P_DATE) {
            ConsoleApp1.ServiceReference1.GetAllStockRequest inValue = new ConsoleApp1.ServiceReference1.GetAllStockRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllStockRequestBody();
            inValue.Body.P_DATE = P_DATE;
            ConsoleApp1.ServiceReference1.GetAllStockResponse retVal = ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllStock(inValue);
            return retVal.Body.GetAllStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllStockResponse> ConsoleApp1.ServiceReference1.serviceSoap.GetAllStockAsync(ConsoleApp1.ServiceReference1.GetAllStockRequest request) {
            return base.Channel.GetAllStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllStockResponse> GetAllStockAsync(string P_DATE) {
            ConsoleApp1.ServiceReference1.GetAllStockRequest inValue = new ConsoleApp1.ServiceReference1.GetAllStockRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllStockRequestBody();
            inValue.Body.P_DATE = P_DATE;
            return ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReference1.GetAllPriceResponse ConsoleApp1.ServiceReference1.serviceSoap.GetAllPrice(ConsoleApp1.ServiceReference1.GetAllPriceRequest request) {
            return base.Channel.GetAllPrice(request);
        }
        
        public string GetAllPrice(string P_DATE) {
            ConsoleApp1.ServiceReference1.GetAllPriceRequest inValue = new ConsoleApp1.ServiceReference1.GetAllPriceRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllPriceRequestBody();
            inValue.Body.P_DATE = P_DATE;
            ConsoleApp1.ServiceReference1.GetAllPriceResponse retVal = ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllPrice(inValue);
            return retVal.Body.GetAllPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllPriceResponse> ConsoleApp1.ServiceReference1.serviceSoap.GetAllPriceAsync(ConsoleApp1.ServiceReference1.GetAllPriceRequest request) {
            return base.Channel.GetAllPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReference1.GetAllPriceResponse> GetAllPriceAsync(string P_DATE) {
            ConsoleApp1.ServiceReference1.GetAllPriceRequest inValue = new ConsoleApp1.ServiceReference1.GetAllPriceRequest();
            inValue.Body = new ConsoleApp1.ServiceReference1.GetAllPriceRequestBody();
            inValue.Body.P_DATE = P_DATE;
            return ((ConsoleApp1.ServiceReference1.serviceSoap)(this)).GetAllPriceAsync(inValue);
        }
    }
}
