//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.RFC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RFC.serviceSoap")]
    public interface serviceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  P_DATE_from 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllVendors", ReplyAction="*")]
        ConsoleApp1.RFC.GetAllVendorsResponse GetAllVendors(ConsoleApp1.RFC.GetAllVendorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllVendors", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllVendorsResponse> GetAllVendorsAsync(ConsoleApp1.RFC.GetAllVendorsRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetAllWarehousesResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWarehouses", ReplyAction="*")]
        ConsoleApp1.RFC.GetAllWarehousesResponse GetAllWarehouses(ConsoleApp1.RFC.GetAllWarehousesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWarehouses", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllWarehousesResponse> GetAllWarehousesAsync(ConsoleApp1.RFC.GetAllWarehousesRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  P_DATE_from 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        ConsoleApp1.RFC.GetAllProductsResponse GetAllProducts(ConsoleApp1.RFC.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllProductsResponse> GetAllProductsAsync(ConsoleApp1.RFC.GetAllProductsRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  P_DATE 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStock", ReplyAction="*")]
        ConsoleApp1.RFC.GetAllStockResponse GetAllStock(ConsoleApp1.RFC.GetAllStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllStock", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllStockResponse> GetAllStockAsync(ConsoleApp1.RFC.GetAllStockRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  P_DATE 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPrice", ReplyAction="*")]
        ConsoleApp1.RFC.GetAllPriceResponse GetAllPrice(ConsoleApp1.RFC.GetAllPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllPriceResponse> GetAllPriceAsync(ConsoleApp1.RFC.GetAllPriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllVendorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllVendors", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllVendorsRequestBody Body;
        
        public GetAllVendorsRequest() {
        }
        
        public GetAllVendorsRequest(ConsoleApp1.RFC.GetAllVendorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllVendorsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_DATE_from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_DATE_TO;
        
        public GetAllVendorsRequestBody() {
        }
        
        public GetAllVendorsRequestBody(string P_DATE_from, string P_DATE_TO) {
            this.P_DATE_from = P_DATE_from;
            this.P_DATE_TO = P_DATE_TO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllVendorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllVendorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllVendorsResponseBody Body;
        
        public GetAllVendorsResponse() {
        }
        
        public GetAllVendorsResponse(ConsoleApp1.RFC.GetAllVendorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllVendorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllVendorsResult;
        
        public GetAllVendorsResponseBody() {
        }
        
        public GetAllVendorsResponseBody(string GetAllVendorsResult) {
            this.GetAllVendorsResult = GetAllVendorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWarehousesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWarehouses", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllWarehousesRequestBody Body;
        
        public GetAllWarehousesRequest() {
        }
        
        public GetAllWarehousesRequest(ConsoleApp1.RFC.GetAllWarehousesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllWarehousesRequestBody {
        
        public GetAllWarehousesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWarehousesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWarehousesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllWarehousesResponseBody Body;
        
        public GetAllWarehousesResponse() {
        }
        
        public GetAllWarehousesResponse(ConsoleApp1.RFC.GetAllWarehousesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWarehousesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllWarehousesResult;
        
        public GetAllWarehousesResponseBody() {
        }
        
        public GetAllWarehousesResponseBody(string GetAllWarehousesResult) {
            this.GetAllWarehousesResult = GetAllWarehousesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllProductsRequestBody Body;
        
        public GetAllProductsRequest() {
        }
        
        public GetAllProductsRequest(ConsoleApp1.RFC.GetAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_DATE_from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_DATE_TO;
        
        public GetAllProductsRequestBody() {
        }
        
        public GetAllProductsRequestBody(string P_DATE_from, string P_DATE_TO) {
            this.P_DATE_from = P_DATE_from;
            this.P_DATE_TO = P_DATE_TO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllProductsResponseBody Body;
        
        public GetAllProductsResponse() {
        }
        
        public GetAllProductsResponse(ConsoleApp1.RFC.GetAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllProductsResult;
        
        public GetAllProductsResponseBody() {
        }
        
        public GetAllProductsResponseBody(string GetAllProductsResult) {
            this.GetAllProductsResult = GetAllProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStock", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllStockRequestBody Body;
        
        public GetAllStockRequest() {
        }
        
        public GetAllStockRequest(ConsoleApp1.RFC.GetAllStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_DATE;
        
        public GetAllStockRequestBody() {
        }
        
        public GetAllStockRequestBody(string P_DATE) {
            this.P_DATE = P_DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllStockResponseBody Body;
        
        public GetAllStockResponse() {
        }
        
        public GetAllStockResponse(ConsoleApp1.RFC.GetAllStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllStockResult;
        
        public GetAllStockResponseBody() {
        }
        
        public GetAllStockResponseBody(string GetAllStockResult) {
            this.GetAllStockResult = GetAllStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPrice", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllPriceRequestBody Body;
        
        public GetAllPriceRequest() {
        }
        
        public GetAllPriceRequest(ConsoleApp1.RFC.GetAllPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_DATE;
        
        public GetAllPriceRequestBody() {
        }
        
        public GetAllPriceRequestBody(string P_DATE) {
            this.P_DATE = P_DATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.RFC.GetAllPriceResponseBody Body;
        
        public GetAllPriceResponse() {
        }
        
        public GetAllPriceResponse(ConsoleApp1.RFC.GetAllPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllPriceResult;
        
        public GetAllPriceResponseBody() {
        }
        
        public GetAllPriceResponseBody(string GetAllPriceResult) {
            this.GetAllPriceResult = GetAllPriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviceSoapChannel : ConsoleApp1.RFC.serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviceSoapClient : System.ServiceModel.ClientBase<ConsoleApp1.RFC.serviceSoap>, ConsoleApp1.RFC.serviceSoap {
        
        public serviceSoapClient() {
        }
        
        public serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.RFC.GetAllVendorsResponse ConsoleApp1.RFC.serviceSoap.GetAllVendors(ConsoleApp1.RFC.GetAllVendorsRequest request) {
            return base.Channel.GetAllVendors(request);
        }
        
        public string GetAllVendors(string P_DATE_from, string P_DATE_TO) {
            ConsoleApp1.RFC.GetAllVendorsRequest inValue = new ConsoleApp1.RFC.GetAllVendorsRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllVendorsRequestBody();
            inValue.Body.P_DATE_from = P_DATE_from;
            inValue.Body.P_DATE_TO = P_DATE_TO;
            ConsoleApp1.RFC.GetAllVendorsResponse retVal = ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllVendors(inValue);
            return retVal.Body.GetAllVendorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllVendorsResponse> ConsoleApp1.RFC.serviceSoap.GetAllVendorsAsync(ConsoleApp1.RFC.GetAllVendorsRequest request) {
            return base.Channel.GetAllVendorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllVendorsResponse> GetAllVendorsAsync(string P_DATE_from, string P_DATE_TO) {
            ConsoleApp1.RFC.GetAllVendorsRequest inValue = new ConsoleApp1.RFC.GetAllVendorsRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllVendorsRequestBody();
            inValue.Body.P_DATE_from = P_DATE_from;
            inValue.Body.P_DATE_TO = P_DATE_TO;
            return ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllVendorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.RFC.GetAllWarehousesResponse ConsoleApp1.RFC.serviceSoap.GetAllWarehouses(ConsoleApp1.RFC.GetAllWarehousesRequest request) {
            return base.Channel.GetAllWarehouses(request);
        }
        
        public string GetAllWarehouses() {
            ConsoleApp1.RFC.GetAllWarehousesRequest inValue = new ConsoleApp1.RFC.GetAllWarehousesRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllWarehousesRequestBody();
            ConsoleApp1.RFC.GetAllWarehousesResponse retVal = ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllWarehouses(inValue);
            return retVal.Body.GetAllWarehousesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllWarehousesResponse> ConsoleApp1.RFC.serviceSoap.GetAllWarehousesAsync(ConsoleApp1.RFC.GetAllWarehousesRequest request) {
            return base.Channel.GetAllWarehousesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllWarehousesResponse> GetAllWarehousesAsync() {
            ConsoleApp1.RFC.GetAllWarehousesRequest inValue = new ConsoleApp1.RFC.GetAllWarehousesRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllWarehousesRequestBody();
            return ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllWarehousesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.RFC.GetAllProductsResponse ConsoleApp1.RFC.serviceSoap.GetAllProducts(ConsoleApp1.RFC.GetAllProductsRequest request) {
            return base.Channel.GetAllProducts(request);
        }
        
        public string GetAllProducts(string P_DATE_from, string P_DATE_TO) {
            ConsoleApp1.RFC.GetAllProductsRequest inValue = new ConsoleApp1.RFC.GetAllProductsRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllProductsRequestBody();
            inValue.Body.P_DATE_from = P_DATE_from;
            inValue.Body.P_DATE_TO = P_DATE_TO;
            ConsoleApp1.RFC.GetAllProductsResponse retVal = ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllProducts(inValue);
            return retVal.Body.GetAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllProductsResponse> ConsoleApp1.RFC.serviceSoap.GetAllProductsAsync(ConsoleApp1.RFC.GetAllProductsRequest request) {
            return base.Channel.GetAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllProductsResponse> GetAllProductsAsync(string P_DATE_from, string P_DATE_TO) {
            ConsoleApp1.RFC.GetAllProductsRequest inValue = new ConsoleApp1.RFC.GetAllProductsRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllProductsRequestBody();
            inValue.Body.P_DATE_from = P_DATE_from;
            inValue.Body.P_DATE_TO = P_DATE_TO;
            return ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.RFC.GetAllStockResponse ConsoleApp1.RFC.serviceSoap.GetAllStock(ConsoleApp1.RFC.GetAllStockRequest request) {
            return base.Channel.GetAllStock(request);
        }
        
        public string GetAllStock(string P_DATE) {
            ConsoleApp1.RFC.GetAllStockRequest inValue = new ConsoleApp1.RFC.GetAllStockRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllStockRequestBody();
            inValue.Body.P_DATE = P_DATE;
            ConsoleApp1.RFC.GetAllStockResponse retVal = ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllStock(inValue);
            return retVal.Body.GetAllStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllStockResponse> ConsoleApp1.RFC.serviceSoap.GetAllStockAsync(ConsoleApp1.RFC.GetAllStockRequest request) {
            return base.Channel.GetAllStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllStockResponse> GetAllStockAsync(string P_DATE) {
            ConsoleApp1.RFC.GetAllStockRequest inValue = new ConsoleApp1.RFC.GetAllStockRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllStockRequestBody();
            inValue.Body.P_DATE = P_DATE;
            return ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.RFC.GetAllPriceResponse ConsoleApp1.RFC.serviceSoap.GetAllPrice(ConsoleApp1.RFC.GetAllPriceRequest request) {
            return base.Channel.GetAllPrice(request);
        }
        
        public string GetAllPrice(string P_DATE) {
            ConsoleApp1.RFC.GetAllPriceRequest inValue = new ConsoleApp1.RFC.GetAllPriceRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllPriceRequestBody();
            inValue.Body.P_DATE = P_DATE;
            ConsoleApp1.RFC.GetAllPriceResponse retVal = ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllPrice(inValue);
            return retVal.Body.GetAllPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllPriceResponse> ConsoleApp1.RFC.serviceSoap.GetAllPriceAsync(ConsoleApp1.RFC.GetAllPriceRequest request) {
            return base.Channel.GetAllPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.RFC.GetAllPriceResponse> GetAllPriceAsync(string P_DATE) {
            ConsoleApp1.RFC.GetAllPriceRequest inValue = new ConsoleApp1.RFC.GetAllPriceRequest();
            inValue.Body = new ConsoleApp1.RFC.GetAllPriceRequestBody();
            inValue.Body.P_DATE = P_DATE;
            return ((ConsoleApp1.RFC.serviceSoap)(this)).GetAllPriceAsync(inValue);
        }
    }
}
